<?php

use Illuminate\Database\Seeder;

class AlgorithmsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){

        // Seed base algorithms for Full PLL 
        $algorithms = [
            ['id' => 1, 
            'name' => 'H-perm', 
            'algorithm' => "(M2 U M2) U2 (M2 U M2)", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'Middle cross',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 2, 
            'name' => 'Z-perm', 
            'algorithm' => "(M2 U M2 U M') (U2 M2 U2 M') U2", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'Middle diagnal swap',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 3, 
            'name' => 'E-perm', 
            'algorithm' => "X' [(R U' R') D (R U R')]  D' [(R U R') D (R U' R')]", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'Corner swaps',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 4, 
            'name' => 'Aa-perm', 
            'algorithm' => "R' (F R') B2 R (F' R') B2 R2", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'Three corner swap',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 5, 
            'name' => 'Ab-perm', 
            'algorithm' => "X' [R2 (B2 R F) R' (B2 R F') R]", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'Three corner swap',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 6, 
            'name' => 'Ua-perm', 
            'algorithm' => "L2 (U' B F') L2 (B' F U') L2", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => '3 middle swap - counter clockwise',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 7, 
            'name' => 'Ub-perm', 
            'algorithm' => "L2 (U B F') L2 (B' F U) L2", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => '3 middle swap - clockwise',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 8, 
            'name' => 'T-perm', 
            'algorithm' => "(R U R' U')(R' F)(R2 U' R') U' (R U R' F')", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'T design',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 9, 
            'name' => 'Y-perm', 
            'algorithm' => "F R U' R' U'(R U R' F')(SXY)(Sledge)", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'base / default algorithm',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 10, 
            'name' => 'Ja-perm', 
            'algorithm' => "(R' U L')(U2 R U' R' U2)(R L U')", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'J left of Front-Face',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 11, 
            'name' => 'Jb-perm', 
            'algorithm' => "(R U R' F)[(SXY)(R' F)(R2 U' R') U']", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'J right of Front-Face',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 12, 
            'name' => 'Ra-perm', 
            'algorithm' => "(R U R' F') R U2 R' U2 (R' F R U) R U2 R' U'", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'Headlights +1 on right',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 13, 
            'name' => 'Rb-perm', 
            'algorithm' => "(R' U2 R U2)(R' F)(SXY)(R' F') R2 U'", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'Headlights +1 on left',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 14, 
            'name' => 'V-perm', 
            'algorithm' => "X'[(sledge) U (R U2 R' U' R U' R') U2 (R U R' U')]", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'V corner ',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 15, 
            'name' => 'F-perm', 
            'algorithm' => "R' U' F' [T-perm w/o last F'] U R", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'Complete side / middle and corner swap',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 16, 
            'name' => 'Na-perm', 
            'algorithm' => "(R U R' U) [Jb Perm] U' R U' R'", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'X top-left to btm-right',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 17, 
            'name' => 'Nb-perm', 
            'algorithm' => "(R' U R U') R' F' U' F (R U R')(F R' F' R) U' R", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'X btm-left to top-right',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 18, 
            'name' => 'Ga-perm', 
            'algorithm' => "R2 U R' U (R' U' R U') R2 (D U' R' U R D')", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'G clockwise - cross',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 19, 
            'name' => 'Gd-perm', 
            'algorithm' => "(R U R') U' D R2 (U' R U' R' U) R' U R2 D'", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'G clockwise - not cross',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 20, 
            'name' => 'Gc-perm', 
            'algorithm' => "R2 F2 R U2 R U2 R' F (SXY)(R' F) R2", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'G counter-clockwise - cross',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            ['id' => 21, 
            'name' => 'Gb-perm', 
            'algorithm' => "(R' U' R) U D' R2 U R' U R U' R U' (R2 D)", 
            'group' => 'cubedThree', 
            'group_status' => 'standard',
            'description' => 'G counter-clockwise - not cross',
            'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            'user_id' => NULL,
            ],
            
        ];

        DB::table('algorithms')->insert($algorithms);
    }
}
